version: "3.8"
services:
  app:
    image: "academy-api"
    build:
      context: ./academy-server/src/main/docker
    container_name: app
    depends_on:
      - psql
    environment:
      - spring.datasource.url=jdbc:postgresql://psql:5432/academy
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.properties.hibernate.format_sql=true
      - server.error.include-message=always
  psql:
    image: 'postgres:16-alpine'
    container_name: psql
    environment:
      - POSTGRES_DB=academy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres